(part "ADE-1+"
    (packageRef "ADE1")
    (interface
        (port "1" (symbPinId 1) (portName "GROUND_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "IF") (portType INOUT))
        (port "3" (symbPinId 3) (portName "RF") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GROUND_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GROUND_3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "LO") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "139-ADE-1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mini-Circuits/ADE-1%2b?qs=xZ%2FP%252Ba9zWqZNkkNe3uAsRQ%3D%3D")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "ADE-1+")
    (property "Description" "RF Mixer Level 7, SMT Double Balanced Mixer, RF/LO Freq 0.5 - 500 MHz")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/ADE-1+.pdf")
    (property "symbolName1" "ADE-1+")
)
