(part "SCPHS-13_6+"
    (packageRef "SCPHS136")
    (interface
        (port "1" (symbPinId 1) (portName "IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GROUND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GROUND_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GROUND_3") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GROUND_4") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GROUND_5") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GROUND_6") (portType INOUT))
        (port "9" (symbPinId 9) (portName "GROUND_7") (portType INOUT))
        (port "10" (symbPinId 10) (portName "BIAS_1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "BIAS_2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "GROUND_8") (portType INOUT))
        (port "13" (symbPinId 13) (portName "GROUND_9") (portType INOUT))
        (port "14" (symbPinId 14) (portName "GROUND_10") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "SCPHS-13.6+")
    (property "Description" "RF IC Phase Shifter Cellular, DCS, PCS 10MHz ~ 16MHz 360 Phase Shift")
    (property "Datasheet_Link" "https://www.minicircuits.com/pdfs/SCPHS-13.6+.pdf?srsltid=AfmBOood8OJ5uavXDNUtbAfkLWqTrYLA4ByT_aWsjahEDcoRM0afmWrr")
    (property "symbolName1" "SCPHS-13_6+")
)
